### ISSUE TITLE
Spam-rightclicking on the Guide makes it skip forward

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#114]
If I spam-rightclick on the guide, it will first go back, but no further back than page 3, and after a slight delay start moving forward through the pages again.

**Comment by Xerus2000** [comment]
I prefer when a guide points somewhere. You know, an arrow that points to every major part of the application and explains it, instead of a static dialog.

**Comment by sghpjuikit** [comment]
Arrow huh. I did implement idea that the guide knows when you complete the action you need to. That's good. But arrow... Thats not easy, not easy at all. Interactivity. Popups and popups with content in sync with content in different windows are brutal.

Certainly lot to think about here.

**Comment by sghpjuikit** [comment]
Guide has been turned into a plugin and can be disabled.

**Comment by sghpjuikit** [comment]
The issue have also been fixed long time ago, due to removal of the `back button guide`.  As for the arrows, well - I'll see what I can do, but I cant promise anything.
