### ISSUE TITLE
"Open" Shortcut is useless

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#124]
There is a shortcut "Open", which defaults to Ctrl+Shift+O. But whenever I press it, none of the actions that show up do anything, because there is no Data.

**Comment by sghpjuikit** [comment]
The issue is definitely not because there is no data, that is the expected behavior. I wont go into details why and I agree it is not user friendly.

Reproduced the problem. I'll have a look soon.

**Comment by sghpjuikit** [comment]
Fixed.

Caused by Kotlin's implicit null check after porting to Kotlin. I also removed actionAppPane and now use actionPane for everything - no need for two separate ActionPane instances. This has numerous advantages I wont go into.
