### ISSUE TITLE
Settings popup does not scroll

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#125]
![image](https://user-images.githubusercontent.com/13354331/50898320-1a4f9980-140f-11e9-8ef2-4aff6db19365.png)

Whenever I open the Settings and go to Shortcuts, the window grows extremely high. I can resize it to be smaller, but it is not scrollable. So, two issues here:

1) The Settings window should keep a consistent size (when I open the Settings in something and then switch to Shortcuts, it resizes)
2) It should be scrollable

Oh, and:

3) You shouldn't be able to close the configurator in the Settings window.  In fact, all these edge actions shouldn't be there.

![image](https://user-images.githubusercontent.com/13354331/50898491-9e098600-140f-11e9-92fc-c8653a4f1408.png)

**Comment by sghpjuikit** [comment]
Yes I caused this problem very recently and already have a local fix. Didnt even have time to push with the constant bombardment of problems haha.

I'm closing this as fixed. Will push in few minutes.
