### ISSUE TITLE
Replacing missing widgets with Empty should only be temporary

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#126]
When I delete some widget folders, the widgets get replaced with "Empty" in the interface, so far so good. But when I restore these widgets, the "Empty" widgets stay. Ideally, the empty widgets would not be persisted, but instead the original widget that was at its place. That would require remembering the original widget data when such a replacing operation is done and then using it when serialising the widget.
This would result in the application checking fir the existence of the widget every startup and potentially save the user quite a lot of hassle reconfiguring it.

**Comment by sghpjuikit** [comment]
Yes, I am aware of this issue, painfully so. I wanted to port Widget.java to Kotlin before tackling this.

**Comment by sghpjuikit** [comment]
Only happens when the factory can not be found during deserialization.

**Comment by sghpjuikit** [comment]
Fixed in #8ee784233d3c7f6d72991b74cd9618416474c92d

This was not easy, but it did turn out simple.

**Comment by sghpjuikit** [comment]
Testing:

1
- Start app
- edit widget so it can compile but not load, for example edit Library widget's fxml file
- widget should reload and display appropriate message
- edit source back to normal
- widget should reload correctly

2
- close app
- remove widget files (entire directory) of widget that was open when app closed
- start app
- the widget should display appropriate message
- put the widget sources back
- widget should reload properly

In all these cases, inputs/outputs should stay properly connected.
