### ISSUE TITLE
Improve missing kotlinc reporting

### ISSUE THREAD

**Issue by sghpjuikit** [sghpjuikit/player#14]
Missing kotlin compiler should report to user and better handle 'missing widgets'. Widget should not be in registered but not compiled state.

**Comment by Xerus2000** [comment]
I think it would be optimal if gradle also managed that, since it's an issue at development time

**Comment by sghpjuikit** [comment]
Sure, but if it is possible.

**Comment by sghpjuikit** [comment]
Widgets can not be registered but not compiled. The problem was in misleading logging. I have fixed that now as well as fixed no logging in case kotlin widget compilation failed.

When kotlinc is missing or unable to compile, developer can see proper logger output. I consider this fixed.
When kotlinc or jvm is missing, an error is logged on app start

I consider this fixed. The gradle integration should be separate issue. Closing this.
