### ISSUE TITLE
Add starter container template

### ISSUE THREAD

**Issue by sghpjuikit** [sghpjuikit/player#143]
To help initial users. See #104 .

**Comment by sghpjuikit** [comment]
Problem with external templates is that they are fragile as they break when Widget/Container classes change state definition (this issue can be improved upon but not entirely removed). That's why I have still not introduced templates.

I will create templates in code, the user templates will/have to be exported into some format (so the fragility will always be there), but initial templates should be pure code.

The remaining problem is how to give user the offer to use them. Still thinking...

**Comment by Xerus2000** [comment]
Loading a template should be one of the options when you click on empty space.

**Comment by sghpjuikit** [comment]
That is already how it works. When you export widget/container/layout it will appear in the widget list. It also uses file monitoring.

Perhaps this could be made explicit to differentiate between `Widget` and `Template`. I will implement this.

This is really just about 'initial' templates that should be suggested when the application is first opened by 1st time user.

**Comment by sghpjuikit** [comment]
Several improvements have been done in order to help 1st time users with layout:
- separated widgets and templates in picker
- 'click to start' placeholder welcomes user in for empty window
- improved placeholder styling & icon behavior
- improved layout/component picker show/hide/content animations to smoothly transition and guide user

Almost done with this.

**Comment by sghpjuikit** [comment]
Fixed in 494e068

The behavior:
- After window is opened, if it detects that it has no content, 1-time placeholder is displayed urging user to just 'Click'. It has additional text for 1st time user how to select initial template
- After user clicks, placeholder closes and layout picker opens. Upon selecting `Template`, there is provided `Playback + Playlist` template. It will always be available. I will add at least 1 more template in the future for Library.

There were also more improvements:
- improved switch container dragging and resizing
- multi-line descriptions in placeholders

**Comment by sghpjuikit** [comment]
I have exported several song table widget configurations like 'Recently played', 'Artists', 'Albums', etc. and plan on adding these as templates. The only problem bundling. So I'm blocked by the following:

Templates are user data (because they are created by user) and I'd like user to be able to take all of his data and move them between installations. But initial templates should survive this.
In theory, the same applies for widgets (and plugins). Technically user-installed widget is user data, but user will probably expect that he needs to copy widgets and data separately. This is why each widget/plugin has its directory and its user directory, where data it produces are placed.
But templates do not have this distinction, because 1 they do not produce data and 2 the initial template issue never occurred to me until now.

I think I like this structure:
application root
- app
 - widgets // all widgets
 - plugins // all plugins
 - templates // initial templates
 - skins // all skins
 - resources
 - vlc
 - lib
 - java
 - kotlinc
- user
 - widgets // all widget user data
 - plugins // all plugin user data
 - templates // all user templates


This has the advantage that besides templates, nothing is duplicated. We really want to avoid multiple directory sources in my opinion.

**Comment by sghpjuikit** [comment]
^ Implemented (without touching non template app structure). As of now user can use several useful library view templates, either using the ui template chooser or invoking `Open ${template_name}` action found in app search (CTRL+SHIFT+I).
