### ISSUE TITLE
Provide installation

### ISSUE THREAD

**Issue by sghpjuikit** [sghpjuikit/player#148]
This issue is supposed to deal with the concept of setting up the application (i.e. download/installation) so we agree on how to implement it and provide an answer as series of steps the user must do. This also touches on the aspect of what an application bundle will contain.

- Will VLC be bundled?
No. It will be autodiscovered if it is installed. Otherwise user will have to set it up.

- Will application without VLC set up support any playback (since we have 'working' javafx.media implementation)?
No. It could, but at this point that implementation is old and I do not wish to support it. Perhaps in the future.

- Will libs be bundled?
Yes. They have to be.

- Will Java be bundled?
No. Perhaps in the future. Reason: it is heavy and I have no time to investigate licencing and JDK vs JRE stuff (the application needs JDK to run).

- Will javac be bundled?
No. But it is bundled with JDK, so making practically yes.

- Will Kotlin be bundled?
Yes. It is just a lib.

- Will kotlinc be bundled?
No. But it must be present, so we will include a discovery/download mechanism to avoid bundling kotlinc with the installation. Remains unimplemented. Also there will be an `use experimental/native kotlinc` option, although right now ekotlinc has a bug and can not be used for our needs.

- Will plugins be bundled?
Yes. Because no user supplied plugin support is implemented yet, all plugins are provided in the `Player.jar`. In the future, some of them (the optional ones) will become external.

- Will widgets be bundled?
Yes. All are external. The application has proper API and UX to handle if user removed all of them. Of course some are essential for proper functionality (Playback, Playlist).

- Will templates be bundled?
Yes. These are called initial templates. Some are in the `app/templates` directory, pure container types are provided through code. We may make `app/templates` read-only. Should we? Dunno.

- What launchers will be bundled?
Jar, exe, sh. Maybe bat in the future. All will provide the same functionality.

And with that:

- Will application be usable once user downloads it?
No, JDK will be missing so it will not start at all. VLC will be missing so playback will not be possible.

- Will this application be portable?
Yes, on all platforms. Means it contains its configuration and user data, does not create files outside its directory and can be safely moved to usb or anywhere else.

Will there be an installation wizzard?
- No. Perhaps in the future. Besides JDK/VLC, it could provide file associations, but I find that to be easily doable manually later on and besides, this being portable application, we better avoid file associations altogether (since moving the application breaks the association).

User installation steps necessary with the above:
- download the application release
- copy/link JDK of correct version to `app/java`
- (optional) install VLC or link/copy its portable installation to `app/vlc`

The application will automate:
- VLC discovery
- kotlinc obtaining

**Comment by sghpjuikit** [comment]
Closed as: I consider the above pretty much final. It was edited and put into initial documentation file, which I'll push soon.

**Comment by Xerus2000** [comment]
About JDK licensing: I am no expert, but I think this shouldn't be a problem with OpenJDK?

**Comment by sghpjuikit** [comment]
I dont know. It was JRE that was made for bundling, not JDK. With newest releases things may be dramatically different. This is low priority for me, but if you can confirm and link some licence/statement then that wouldnt hurt. But there's also the issue of creating a giant bundle (for each OS) and hosting it here, particularly when we can expect major changes and many releases.

**Comment by sghpjuikit** [comment]
see https://github.com/sghpjuikit/player/tree/master/app/documentation

**Comment by Xerus2000** [comment]
@sghpjuikit please give the file the `.md` ending so that GitHub properly displays it ;)
