### ISSUE TITLE
Can extfx be removed?

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#19]
extfx doesn't seem to receive any activity anymore, and I can't even find any use of it in the source code. Can I remove it?

**Comment by sghpjuikit** [comment]
It is indeed being used in the project for creating mathematical functions from user supplied values (text, e.g. "x*x+10"). I'm not against using a more recent substitute, but that would require modifying the code. See the StrExF class.

**Comment by Xerus2000** [comment]
Nope, that class actually uses exp4j. I've searched through the project multiple times, and I'll be removing extfx on the gradle branch now.

**Comment by sghpjuikit** [comment]
Oh right, I mistook exp4j for extfx, In that case, I think it can be removed.
