### ISSUE TITLE
MP3 CBR Playback issue

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#2]
When playing MP3 CBR files, some don't work. Out of about 50 I got here, exactly 3 did not work. It is not an issue with JavaFX Player since my application plays them fine.

These are the 3 files in a zip:
30 day link: https://ufile.io/p4rau
permanent link: https://mega.nz/#!Zcp1UKhT!AGGevvfyFHeO3B1TtbW97HOpIkVjnHoRdKW95ow18Sw

**Comment by sghpjuikit** [comment]
Thx for clarifying the issue to not lie in the JavaFX MediaPlayer.

I'll investigate the issue and add the files to the test suite of audio files. It may be a good idea to push the suite to the repo.

**Comment by sghpjuikit** [comment]
Using vlcj internally for playback solved this.
Not the root of the issue, but JavaFX MediaPlayer is no longer used (it may be used as a fallback) and that deprecates this issue.
