### ISSUE TITLE
Update Development section in Readme to clearly explain gradle

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#20]
start has been made with 2759de042b33d21cb379fa15be9e0105f0f9367f

**Comment by sghpjuikit** [comment]
I'm afraid this is going to be your job after you have managed to set it up. Your thoughts?

**Comment by Xerus2000** [comment]
look who's assigned ;) it's just a personal todo

**Comment by sghpjuikit** [comment]
Never mind then. Good work.

**Comment by Xerus2000** [comment]
I am currently strongly in favor of creating a separate CONTRIBUTING.md if you don't want to use the wiki

**Comment by sghpjuikit** [comment]
Ok.

The problem with wiki is that it falls outside of the scope of the project. While it appears to be possible to integrate it in the main repository (as submodule), I do not see it as a good approach.

I have no problem with dividing the README into multiple (interlinked) files with README as a root. If the .md files start to get out of hands, we could consider wiki, but I believe we should not get to that point.

I think it may make sense to have SKINS.md in skins, WIDGETS.md in widgets and PLUGINS.md in plugins. This would turn the readmes into a wiki, while serving a specific use to user/developer.

**Comment by Xerus2000** [comment]
But I'd be careful not to clutter it with md files - plugins and skins would only be a few lines each...

**Comment by Xerus2000** [comment]
basically implemented in 78e7b35a604604755a1bf9208194491f429f111a

**Comment by sghpjuikit** [comment]
I find that not satisfactory (I have observation that backs it up).

- The minimum is to exactly write numbered steps to completely setup and run the project (with no IDE) and optionally with IDE as well. The steps must contain exact commands in exact order and explain the minimum required knowledge about the commands.
- I'd also like to see explained the purpose of the gradlew files, gradle wrapper, gradle build files and the structure of the project (out of scope here).

**Comment by sghpjuikit** [comment]
The explanations can be in one line, it's merely so the dev does not run the commands blindly and that he has the necessary keywords to search and familiarize himself with the build tools.

Yeah.

**Comment by Xerus2000** [comment]
I think #50 sufficiently adresses this, so I will close this.
