### ISSUE TITLE
Find a way to compile kotlin on linux

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#21]
The current way of using the Kotlin compiler only works on Windows, that's why the configurator and terminal widgets, which are already in Kotlin now, currently don't work in Linux

**Comment by sghpjuikit** [comment]
I think this is priority #1 at this point. It will require your cooperation until I'll set up some Linux dev environment.

**Comment by Xerus2000** [comment]
yep, that's why I self-assigned it for now

**Comment by sghpjuikit** [comment]
I''l do some work on this and push and letyou know.

**Comment by sghpjuikit** [comment]
The Kotlin widgets should compile fine now on Linux and the process of widget (factory) life-cycle should be better logged as well.

Please, confirm the functionality works as expected.

**Comment by Xerus2000** [comment]
Yes, it works now!
