### ISSUE TITLE
Fix widget dependency on jts

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#23]
Both Voronoi and Comet depend on jts and don't compile, even though the jar is in my widgets directory. But it is apparently not recognised by the application.

```
45:27.734 I [JavaFX Applicat] WidgetManager - Compiling widget=Voronoi
45:27.735 I [JavaFX Applicat] WidgetManager - Compiling widget=Voronoi
/home/janek/Projects/PlayerFX/working dir/widgets/voronoi/Voronoi.java:3: error: package com.vividsolutions.jts.geom does not exist
import com.vividsolutions.jts.geom.Coordinate;
                                  ^
/home/janek/Projects/PlayerFX/working dir/widgets/voronoi/Voronoi.java:4: error: package com.vividsolutions.jts.geom does not exist
import com.vividsolutions.jts.geom.Envelope;
                                  ^
/home/janek/Projects/PlayerFX/working dir/widgets/voronoi/Voronoi.java:5: error: package com.vividsolutions.jts.geom does not exist
import com.vividsolutions.jts.geom.Geometry;
                                  ^
```

**Comment by sghpjuikit** [comment]
I think I should simply pull both widgets from the repo - they serve personal purpose. That would solve the problem. What do you think? Otherwise this is blocked until I'll work out the gradle configuration you did.

**Comment by Xerus2000** [comment]
But it shouldn'T have to do with gradle. The player is launched into the working dir and should do its thing. The only thing that might cause this is that there's now a build.gradle file in the widgets dir.

**Comment by sghpjuikit** [comment]
Hm. I dont like the idea of build.gradle in there. I'll be able to say more only after I work out Gradle.

**Comment by Xerus2000** [comment]
I just pushed to the gradle branch, you could pull it and test. It's not optimised and extensively tested by me yet, but the readme should provide you with the most important command: `./gradlew run`

**Comment by sghpjuikit** [comment]
I disabled widget lib sharing (it was a temporary workaround anyway), so I consider this fixed.
