### ISSUE TITLE
Find a good branding for the Player

### ISSUE THREAD

**Issue by xeruf** [sghpjuikit/player#24]
I think for an actual Release, we need to brand it. Since Player is pretty non-telling, I think PlayerFX is the way to go - short and descriptive. So I suggest we impart that everywhere where currently it is only called player. What about even renaming the repository?

**Comment by sghpjuikit** [comment]
Yes. PlayerFX seems like a reasonable choice although there is no need to stick to the FX nomenclature (nor Java or Kotlin one). In addition, there seem some projects out there, for example FXPlayer, so it may be good idea to come from other direction. I have no idea here and am open to suggestions.

By the way, the project does have (fairly decent) icons I think, I think those can stay.

**Comment by Xerus2000** [comment]
I do agree, for the icons: Those in extra or those in the working dir? They seem to have inverted colors

**Comment by sghpjuikit** [comment]
Those are different designs.

**Comment by Xerus2000** [comment]
I would prefer the alternate design in the extra folder, since the blue on white background seems more fitting to the overall style of the application

**Comment by sghpjuikit** [comment]
I renamed the application to `Spit Player` to avoid conflicts with projects with very similar names and to avoid using technology as a trademark. The name is now consistent with package names and my domain name. I also updated the documentation and all the other references.

It can be argued the name is distasteful, but it is what it is. It is my trademark and it is unique.

Done in a5d8fec.

**Comment by sghpjuikit** [comment]
Icons can still be changed later if we really need.
Renaming repository seems quite dangerous. Sooner better than later, but perhaps never is for the best? https://help.github.com/en/articles/renaming-a-repository

**Comment by sghpjuikit** [comment]
I consider this done. I'll add github repo tags after next release.

**Comment by Xerus2000** [comment]
> Icons can still be changed later if we really need.

why would we need to?

> Renaming repository seems quite dangerous. Sooner better than later, but perhaps never is for the best? https://help.github.com/en/articles/renaming-a-repository

why should it be dangerous? the only conflict that could ever arise is if you created another repo with the name "player" in your account, which you simply wouldn't do

**Comment by sghpjuikit** [comment]
You mentioned changing the icons. I meant that it can be done anytime and put it out of scope of this issue.

It is dangerous because it changes the public URL of the project. Even if Github does support redirect from the old one.

If you really wish, we can rename the repo. Must be before next release

**Comment by sghpjuikit** [comment]
It has come to my attention that this repo weights 200MB. This is due to large binary files commited years ago. git gc, prune and any of the git magic can not help here as these files are still referenced by commits.

There is a git filter and the like, which would help, but change hash of every commit, which seems to me like a bad idea due to commit references in the issues.

However, if we are to rename the repository anyway, we may as well create a new one and migrate issues over there. We could start anew or squash first couple commits (ancient history), which would also allow us to dereference the binary files.

**Comment by Xerus2000** [comment]
That might be a good idea. I'd definitely like to keep the history and just use https://rtyley.github.io/bfg-repo-cleaner/ to remove the big files from history.

But I'm not sure whether it's worth to drop all the issues and PRs that we have in this repo just for that. I think it might be a better idea to simply rename the repo and remove the big files from history to remove those files, so that merged PRs and Issue discussions stay intact.

**Comment by sghpjuikit** [comment]
As far as I know there is no way to remove a file from history without changing the commit hash, and no way to change a commit hash without changing hash of every commit that comes after it. I may be wrong.

**Comment by sghpjuikit** [comment]
Perhaps we could do this:

```
git checkout to-be-1st-commit
git checkout -b to-be-master-branch
git reset --soft 1st-repo-commit
git commit
git cherry-pick every-comit
```

would squash all changes before certain commit into single commit and then apply remaining commits on top. Should be conflict-free. This does not change history, it creates new one, right? So would it preserve hashes? What if all existing branches got deleted and gced?

**Comment by Xerus2000** [comment]
> As far as I know there is no way to remove a file from history without changing the commit hash, and no way to change a commit hash without changing hash of every commit that comes after it. I may be wrong.

This is correct.

> ...would squash all changes before certain commit into single commit and then apply remaining commits on top. Should be conflict-free. 

Indeed

> This does not change history, it creates new one, right? So would it preserve hashes? What if all existing branches got deleted and gced?

You can not change anything and preserve hashes. A cherry-pick will at least change the time and thus get a new hash.

Btw, I have a bash/zsh function that does what you want:
```zsh
# Rewriting history

# gets the AuthorDate of a given committish
git-authordate() {
	local date=$(git log --pretty=fuller --date=raw -1 $1 | grep AuthorDate)
	echo ${date##*: }
}
# executes a git command (usually commit) with the date of a given committish
git-withdate() {
	date=$(git-authordate $1)
	GIT_AUTHOR_DATE="$date" GIT_COMMITTER_DATE="$date" git "${@:2}"
}

# takes all changes in the current working tree and amends them to the given commit
gitedit() {
	git stash
	gitcommits -q $1
	git reset --hard $1
	git stash pop -q
	git-withdate $1 commit --all --amend "${@:2}"
	gitcommits
}

# takes two committishs and squashes them with all commits between them into a single commit
# this will rewrite the full history from then on, but should not create any conflicts
gitsquash() {
	local -a options
	while [ $# -gt 0 ]; do
		case $1 in
			-i) ignore=true; shift 1;;
			-f|--force) force=true; shift 1;;
			-*) options+=($1); exit 1;;
			*) break;;
		esac
	done

	((#!=2)) && echo "Usage: [options] <startcommit> <endcommit>" && return 1
	[[ -n $(git status -s) ]] && [ ! $force ] && echo -e "Tree is dirty, commit or stash your changes first!\nIf you want to execute the command regardless, run again with --force" && return 1

	1=$(git rev-parse $1)
	2=$(git rev-parse $2)
	[ $(git rev-list $1 --count) -lt $(git rev-list $2 --count) ] && t=$1 && 1=$2 && 2=$t

	gitcommits -q $1
	git reset --hard $1
	if [ $(git rev-list $2 --count) = 1 ]; then 
		git update-ref -d HEAD
		git add .
		git-withdate $1 commit -c $1
	else 
		git reset -q $2
		git add .
		git commit --amend
	fi
	gitcommits
}

# given a committish, this command saves a list of commits between the HEAD and the given committish into the .git directory
# when ran without parameters it applies the saved list of commits onto the current HEAD
gitcommits() {
	verbosity=1
	while [[ $# -gt 0 ]]; do
		case $1 in
			-v) verbosity=2; shift 1;;
			-q|--quiet) verbosity=0; shift 1;;
			--theirs) params=(-X theirs); shift 1;;
			*) break;;
		esac
	done

	stashed="$(git rev-parse --show-toplevel)/.git/stashed-commits"
	if [ $1 ]; then 
		if [ $verbosity -eq 0 ]
			then git rev-list --reverse HEAD...$1 >$stashed
			else git rev-list --reverse HEAD...$1 | tee $stashed
		fi
	else
		local aborted
		for commit in $(cat $stashed); do
			[ $aborted ] && rest+=($commit) && continue
			[ $verbosity -gt 0 ] && git --no-pager log --oneline -1 $commit
			git-withdate $commit cherry-pick $commit ${params:0} >/dev/null
			last=$?
			[ $last -gt 0 ] && aborted=true && typeset -a rest && continue
			[ $verbosity -gt 0 ] && echo -e "\e[1A$(git log --color=always --pretty=format:"%C(yellow)$(git rev-parse --short HEAD^^)%C(bold) -> %Creset%C(yellow)%h%Creset %s" -1)"
			[ $verbosity -gt 1 ] && git status -s
		done
		echo $rest >$stashed
		[ $aborted ] && echo "A problem was encountered. Fix it and run 'gitcommits' again to apply the remaining ${#rest} commits."
	fi
}
```

You will create a new history regardless, but if you plainly force-push it into this repo we will at least keep all the dicussions we had here and only have to do a hard reset in our local repos.

**Comment by sghpjuikit** [comment]
Closing as done.
