### ISSUE TITLE
Clean up skins

### ISSUE THREAD

**Issue by sghpjuikit** [sghpjuikit/player#27]
Remove incomplete and experimental skins

**Comment by Xerus2000** [comment]
Older Skins Need to either be purged or updated. 

The newer skins should also be separated into multiple files to make adjustments easier.

Furthermore, Skins (referring to Main) should extend Modena.css instead of copying and modifying ist values.

**Comment by sghpjuikit** [comment]
1 True, but that requires an effort I'm currently not willing to give. Feel free.
2 What do you mean multiple files? I don't find the idea of multi-file skins entrancing.
3 There is no need to extends (correct word would be import) from Modena. Modena is always applied, skin thus overrides its values.

Following this, I think it may make sense to have an "AppSkin" which contains the definitions the application uses but are not in Modena and have every skin import this file. This would make standard skin relatively small.

Note: 
- fully functional skins: Main, Flow (extending Main) and FlowNoBgr (extending Flow).
- functional skins: Light, though it is a little outdated (needs some color/contrast tweaks)
- rest: is experimental or unnecessary and can be removed, although there may be some interesting ideas. If you are going to throw these away, i'll put them to my ignored directory, just in case I'll play around with skinning in the future.

Template:
The main template skin every skin should import is Main.css. Unfortunately it is an edited version of old Modena, which makes it a bit difficult to clean up. It may make more sense to start from scratch:
- copy/retain all non-Modena classes as they are
- override necessary Modena classes. The only thing that needs to be done here is removing the bgr colors to allow transparency in panes and controls and some minor tweaks, but even that may add up to some serious work.

**Comment by sghpjuikit** [comment]
I'm closing this.

All non-100%-operable skins were removed.

PS: Main.css is not split. It should merely have all Modena code removed (which entails finding all custom pieces...).

**Comment by Xerus2000** [comment]
1. Light didn't sound bad considering that the application is already quite heavy

2. Please use the fixes # message in commit messages or mention the relevant commit while closing.

Fixed by

**Comment by sghpjuikit** [comment]
1 I have created a FlowNoBgr skin (which is now default) as a lightweight skin. It should be given more sensible name.

2 Ok.

**Comment by sghpjuikit** [comment]
I have made a lot of styling improvements recently. We are now down to 2 skins:
- Main - default
- Flow - Main skin with more effects. The skin is completely rewritten and super-clean
