### ISSUE TITLE
What is the folder "plugins" for?

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#31]
There is only one thing in there, screen rotator, of which I don't know what it does.

**Comment by sghpjuikit** [comment]
Plugins are still not fully implemented in that they do not support runtime compilation like widgets do, but this will definitely be done. Soon I hope. Plugin is, simply put, a widget without ui and can be started/stopped. The usefulness is in the ability to add in a (possibly unrelated) functionality, which would normally require developer to make his own application.

This way even relatively inexperienced developer can conveniently make useful functionalities. E.g.: shortcuts for rotating screen or application launcher. Anything.

For now, the plugins are part of the applications (there are two or three), but they will be moved out, just like the widgets.

**Comment by sghpjuikit** [comment]
@Xerus2000 
Can I close the issue?
