### ISSUE TITLE
Opening the File Chooser on Linux instantly crashes the player

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#33]
It opens a blank file chooser window and then instantly crashes. The issue seems to lie in JNA.
[hs_err_pid12804.log](https://github.com/sghpjuikit/player/files/1665968/hs_err_pid12804.log)

**Comment by sghpjuikit** [comment]
How did you come to the conclusion that JNA is related to this?

I'd like for you to make a very simple JavaFX application/demo that opens a standard JavaFX File dialog and see it the problem persists. The file chooser should just work.

**Comment by Xerus2000** [comment]
A directory chooser I tested worked without issue, but I will investigate further.
This screenshot shows how it looks for literally a splitsecond before the crash:
![](https://user-images.githubusercontent.com/13354331/35652846-c1262da6-06e5-11e8-9789-cdb289a6e12b.png)

**Comment by sghpjuikit** [comment]
Thx for the report. I will try setting up a Linux VM to reproduce and fix the issue.

**Comment by sghpjuikit** [comment]
This may be a bug on your side. I'm running VM with Linux Mint using Vmware on Windows and I am able to open both directory and file chooser.

I'm running
- (latest official) Linux Mint 18.3 Sylvia
- on OracleJDK 9.0.4+11
- I launched the application manually (no IDE, no script) from working directory with command like ./jre/bin/java -cp '.:PlayerFX:lib/*" sp.it.pl.main.AppUtil

**Comment by sghpjuikit** [comment]
Because I can not reproduce this I can not test workarounds.

One possible cause I can imagine is the extension filter. Please see Environment.class and chooseFile/chooseFiles methods and remove the line setting the extensions: this.extensionFilters += extensions.

**Comment by Xerus2000** [comment]
wait how does the application work without the add-opens?

I'll test that when I get back to my PC

**Comment by sghpjuikit** [comment]
I havent included the add-opens here for brevity. I have included it in the launch command.

**Comment by Xerus2000** [comment]
nope, removing the extensionfilters still didn't work

**Comment by sghpjuikit** [comment]
This may be a threading issue (Javafx vs Swing), one of the FileChooser parameters, JDK bug or OS bug. I will continue to try to reproduce the behavior, but until then you can try to eliminate possibilities. For example, what happens if you open some FileChooser in the App.init() or App.start() method? And so on.

**Comment by Xerus2000** [comment]
at least I can drag in songs as a workaround ^^

**Comment by Xerus2000** [comment]
New resources to note:

https://stackoverflow.com/questions/23176624/javafx-freeze-on-desktop-openfile-desktop-browseuri

https://java.wekeepcoding.com/article/11655212/Javafx+using+directory+chooser+crashes+app+under+linux

https://github.com/kwhat/jnativehook/wiki/ThreadSafety#working-with-javafx

**Comment by sghpjuikit** [comment]
I'm opening this as the solution is only a workaround.

**Comment by sghpjuikit** [comment]
Is this issue back?

**Comment by Xerus2000** [comment]
Hmpf... I'll look into it later ^^

**Comment by sghpjuikit** [comment]
I coincidentally found a bug report on JavaFX11 crashing on Linux with Wayland due to gtk3 or something.
But first try isolating jnativehook, since it is the primary suspect. Classes are ActionManager and Hotkeys. The library must not load. Just a heads up since we already confirmed it loads eagerly and unpredictably in a static initialization block.

**Comment by Xerus2000** [comment]
I have Xorg though, not Wayland. Let's see...

**Comment by Xerus2000** [comment]
I have created a little test project with JNativeHook 2.1.0, called `GlobalScreen.registerNativeHook()`, launched the application and showed a file chooser. No problems...

**Comment by sghpjuikit** [comment]
I know this issue must be quite annoying, but I am unable to reproduce it. I will give it another shot.

Pls try removing the library altogether and make Hotkeys just do nothing and test the behavior.

**Comment by sghpjuikit** [comment]
I think I may have figured this out. Please try removing lines 27-31 from Hotkeys.class. The code that silences the logger:
```
    constructor(executor: (Runnable) -> Unit) {
        this.executor = executor

        // Disable library logging.
         java.util.logging.Logger.getLogger(GlobalScreen::class.java.getPackage().name).apply {
             level = java.util.logging.Level.OFF
             useParentHandlers = false
         }
    }
```
I think that ```GlobalScreen::class.java.getPackage()``` triggers GlobalScreen class initialization. I moved this code from start() to constructor, in hopes of removing some of the undesirable library logging.

PS: version 2.1.0 removes some of the undesirable output. If this fix works, could you try if 2.1.0 is unusable? All I know is what the comment in build script says: that 2.1.0 causes critical issue on Linux.

**Comment by Xerus2000** [comment]
> All I know is what the comment in build script says: that 2.1.0 causes critical issue on Linux.

Yes, because that is true. There have been a few reports which point a particular library that it uses since 2.1.
I have also submitted a PR, let's see how he reacts: https://github.com/kwhat/jnativehook/pull/251

I will try what you've suggested, sounds like a good pointer.

**Comment by Xerus2000** [comment]
Found the culprit: `isGlobalShortcutsSupported` is true by default, on every OS. Didn't we set this to be false on Linux?

**Comment by Xerus2000** [comment]
> version 2.1.0 removes some of the undesirable output

Not really. I have done a test with 2.1 and the spam is still insane.

**Comment by sghpjuikit** [comment]
But if the library is not used, it does not cause an issue right? SO isnt it safe to use 2.1.0?

Not exactly. In my testing I confirmed global shortcuts to work on my Linux Mint. Hence global shortcuts on Linux are supported. However due to potential problems on some systems, we set global shortcuts to be disabled on Linux by default. Everything looks good and unless you changed your settings, the library should not load. You should have the following default values on your system:
Global shortcuts supported: true
Global shortcuts enabled: false

2.1.0 removes the licence header and some other things. The logging suppression still needs to be there, but then there is no visible output at all. That is why I'd prefer to use 2.1.0.

**Comment by Xerus2000** [comment]
Hah, jnativehook isn't the culprit apparently! I have removed it and JNA completely from the application and the filechooser still crashes...

The problem was that Hotkeys shouldn't even have been initialized. But when shortcuts are enabled but not supported, ActionManager calls `stopGlobalListening` which calls `hotkeys.stop` which initializes Hotkeys. Anyways, time to find the actual culprit.

**Comment by Xerus2000** [comment]
> I see. I'm going to fix this behavior right away is that ok?

I have created a Hotkeys branch to fix this whole stuff, will push it soon. How do you want to fix that?

**Comment by Xerus2000** [comment]
> How is that a problem when jnativehook/hotkeys do not cause the trouble for you? It may not be correct, but it is not a problem right?

But if it were, it would have been bad. It is not a problem right now, but jnativehook seems to me a pretty unstable thing, who knows if it breaks something again.

> All the more reason to test 2.1.0, can you pls do that after I fix the initialization?

I will

**Comment by Xerus2000** [comment]
Okay, removing terminal and comet widget didn't suffice, but I just removed all widgets except configurator and dirViewer and it worked! Now I'll try to isolate the widget at fault here...

**Comment by Xerus2000** [comment]
btw, please prefix text with > for quoting instead of using quotes, it highlights the text properly.

**Comment by Xerus2000** [comment]
Now it just works without problems in master. What the heck. I will reopen if it returns.

**Comment by Xerus2000** [comment]
It may also be related to my system. I can soon test it on my computer at home to see if it is related to the player or the system.

**Comment by Xerus2000** [comment]
Whenever I was debugging, I used `clean run`, so it is unlikely to be related to cache/data

**Comment by sghpjuikit** [comment]
I noticed you modified clean to delete user/tmp directory. May be related.

**Comment by Xerus2000** [comment]
No, I modified it to delete lib. But since I now have all libs back again since it just somehow works, this doesn't make a difference either.

**Comment by sghpjuikit** [comment]
You added this line to clean task:
`dirWorking/"user"/"tmp",`
This deletes user temp directory, which contains some of the loaded native libraries, including jnativehook, imageio, jna, terminalfx.

I find it hard to believe you can not download Java 10. Do not use Oracle, but OpenJDK? Dunno.

I noticed you started playing around with JDK11, but I'm afraid it will open more then few can of worms with jigsaw, forced modularity, backward incompatible changes in Java APIs, more internal API's hidden as well as JavaFX. If you do make it work - great, but do not waste much time, we can work on 10 at least until 12.

**Comment by Xerus2000** [comment]
1) This line has been in clean task for a very long time. If you are referring to the hotkeys branch, then look again.
2) OpenJDK doesn't have JavaFX either.
3) No, no worms. It works without problems, see my PR.

**Comment by sghpjuikit** [comment]
1 I saw the + sign in the commit so I assumed. Ok.

2 Right. Then I guess there's is an installation floating around somewhere.

**Comment by sghpjuikit** [comment]
The actual culprit behind this issue may be vlcj. See https://github.com/caprica/vlcj/issues/834
I am about to push vlcj4, which has a fix for this. Hopefully this will be completely gone now.
