### ISSUE TITLE
Log levels should not be ordered alphabetically

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#34]
The log levels in the settings are ordered alphabetically, but they should be ordered by the meaning of the levels
![image](https://user-images.githubusercontent.com/13354331/35440951-ed887d74-02a1-11e8-8b68-fb2fc602f3af.png)

**Comment by sghpjuikit** [comment]
The problem lies in the fact that rthere is an alphabetical order imposed on the elements of each combobox in configuration, but sometimes this is unwanted. I will implement this through Constraint annotation which would tell to preserve the original order.
