### ISSUE TITLE
Player becomes uncontrollable when playlist contains only unplayable items

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#35]
When the playlist contents can't be played for whatever reason (in this case because vlc isn't present), then the player indefinitely cycles through all the Songs and is not stoppable. The only option is closing it. 

A simple and good solution would be to add a one second delay before skipping an unplayable item, therefore the user has time to realise what is wrong.

[log_contents.log](https://github.com/sghpjuikit/player/files/1667780/log_contents.log)

**Comment by sghpjuikit** [comment]
There is a mechanism to prevent this, however when VLC is not present, it is bypassed. Known issue. It isnt difficult but there may be better and worse ways to go about handling this.

**Comment by sghpjuikit** [comment]
Fixed 8b21efa34b2798a2bf29a19ba812f2405562daf1

As mentioned there are two reasons for being unable to play a song: invalid song or problem with the underlying player (javafx/vlc). The former is properly defended against. The latter has two situations: unable to play current song or unable to play any song at all. This determines whether we attempt to play next song in line.
