### ISSUE TITLE
Player crashing on Song end

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#37]
This does not happen always, and I'm not yet sure when it does, but sometimes it simply exits after finishing a song.
[hs_err_pid13702.log](https://github.com/sghpjuikit/player/files/1667976/hs_err_pid13702.log)

**Comment by sghpjuikit** [comment]
I know of possible StackOverflowException happening when song ends/starts, which I havent fixed yet, but it is very rare. I have also noticed vlcj crashing few times. This needs more data, so i'ts more or less on hold until then.

How often does this happen on your system?

**Comment by Xerus2000** [comment]
Within playing about 5 songs, it happened twice

**Comment by sghpjuikit** [comment]
It could depend on the type of song and numerous other things, but I'm not experiencing this issue. I'm using VLC 2.2.6.

For start I can only recommend trying greater sample of audio files.

**Comment by sghpjuikit** [comment]
Since VLC 3 came out, it may be worth a shot to use [vlcj for it](https://github.com/caprica/vlcj/tree/experimental)

**Comment by sghpjuikit** [comment]
Update: I do experience this issue on Windows, albeit very rarely (probably somewhere in range of 1/100-1/1000 playbacks). I also think it tends to happen under some condition - I do not remember this happening outside development (I did experience crashed on key presses, but that points to jnativehook probably).

So after some time passing and using later lib versions: how often do you experience this issue?

This could be related to VLC version. Also: I think there is a vlcj branch for VLC3 right?

**Comment by sghpjuikit** [comment]
Update: I have improved vlc player state handling/observing (its in master branch). I'm currently observing the behavior.

**Comment by sghpjuikit** [comment]
vlcj 4 has been recently released, I will adopt it soon.

**Comment by sghpjuikit** [comment]
Should be fixed in f200ce9.

I'm closing this. Of course, I'll be monitoring the situation on my end.
