### ISSUE TITLE
Kotlin widgets do not compile on Linux

### ISSUE THREAD

**Issue by sghpjuikit** [sghpjuikit/player#41]
I have managed to reproduce the issue.

For some reason kotlinc throws an IOException _java.io.IOException: .../jre/jrt-fs.jar not exist. The file exists in jre/lib directory, just like on Windows and this is correct (moving the jat to /jre will allow the compiler to proceed, but then causes a failure due to the file residing in wrong location. This could be an issue on my system only, since this was not reported in the original bug.

There was however an issue of using ";" classpath separator on Linux, while ":" is the correct value. I pushed the changes, so pls @Xerus2000 try now, if it helped for you.

**Comment by Xerus2000** [comment]
Nope

```
2018-02-13 23:08:36,999 ERROR [JavaFX Applicat] sp.it.pl.layout.widget.WidgetManager - Widget=Terminal compilation failed
2018-02-13 23:08:38,586 ERROR [JavaFX Applicat] sp.it.pl.layout.widget.WidgetManager - Widget=Image compilation failed
2018-02-13 23:08:38,941 ERROR [JavaFX Applicat] sp.it.pl.layout.widget.WidgetManager - Widget=Configurator compilation failed
```

**Comment by Xerus2000** [comment]
I found the issue, the Linux permission system prevented me and thus also the player from executing kotlinc. I fixed it and filed a pull request.

**Comment by sghpjuikit** [comment]
I see. It seems odd however that the file would not be executable. Any thoughts on this? Feels like a hack to me.

**Comment by Xerus2000** [comment]
No it isn't. It's a safety gate in Linux to prevent unauthorized scripts from executing.

**Comment by sghpjuikit** [comment]
Ok.
