### ISSUE TITLE
Use info.json instead of @Widget annotation

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#45]
While the @Widget annotation has worked fine until now, I would propose to replace it with an info.json containing its content. This separates widget information from sourcecode, which will be especially important once an ExtensionManager is developed.

**Comment by sghpjuikit** [comment]
I was considering this at the time of making the annotation, but the simplicity of the design through annotation as well as type-safety and correctness of the approach far out-weighted this alternative. I will put this under re-consideration, but to sum it up, the whole idea depends on how this so called ExtensionManager should work.

What is an extension (widget, plugin, service, ...). Who will make an extension and how, why is a manager needed and what would it manage?

I believe what you have in mind is a WidgetManager widget, which would display available widgets and perhaps allow deleting/uninstalling existing widgets as well as installing new (how, from where). I think such widget would be a good idea, although for now its purpose is fulfilled by LayoutChooser , which also displays component information. It is not well suited for this, but it was enough for now.

The idea of the json is not bad, but I think the widgets need to ripe first. Once WidgetManager.java is cleaned up and widget management within the app more robust (this also involves how layouts are integrated into windows) and plugins are also ready, then we can look into more advanced management by the user through the application itself.

**Comment by Xerus2000** [comment]
ExtensionManager is supposed to manage widgets and plugins. I can easily set up a small website for hosting them for free. But for updating an extension from remote it should first fetch the information and then the actual extension if needed.

**Comment by sghpjuikit** [comment]
I see where you are going with this. I'm not sure a widget website is something that we should be concerned about right now. But it is a possibility.

**Comment by Xerus2000** [comment]
Yeah it is mainly a perspective, but since it is something that is very likely when the Project expands, we could already take some steps towards it now

**Comment by sghpjuikit** [comment]
I'd be very surprised to see the project expand to see tens of widgets and requiring a centralized solution and even if, implementing all this would be premature and only waste of effort. Features have a "right time". Implementing too soon adds maintenance and other costs for no benefit. Even worse, it risks that the final requirements/specifications will change, rendering the effort truly a waste.

**Comment by sghpjuikit** [comment]
I'm thinking this could be done by making the companion object of the Widget's Controller implement Widget.Info interface.

I dislike the json idea because it doesnt really provide anything the annotation can not already provide, yet it has fair amount of disadvantages. I would consider (in a long run) a markdown readme file that would play along the companion object.

**Comment by Xerus2000** [comment]
Note by past self: The Annotation is nice for now, but I think it's somewhat abusing annotations and increases cohesion between widgets and the main application.

**Comment by Xerus2000** [comment]
Okay, I'll close this for now.

**Comment by sghpjuikit** [comment]
Perhaps we could generalize the problem to something like: 
- `Broaden widget life cycle to involve widget factory`
- `support widget versioning`
- 'implement remote widget store' or something'

I think it is way too soon to face these issues, but I do agree they may be necessary to solve and yours is a viable way to go around that
