### ISSUE TITLE
Configure gc

### ISSUE THREAD

**Issue by sghpjuikit** [sghpjuikit/player#46]
Gc should return free heap back to OS. Investigate various garbage collectors and configurations for this.

Some useful resources:
[gc types](https://www.stefankrause.net/wp/?p=14)
https://blog.gceasy.io/2017/10/17/43-gc-logging-flags-removed-in-java-9/
http://openjdk.java.net/jeps/158

**Comment by Xerus2000** [comment]
I don't know if you have done anything regarding this yet, but I'm currently heavily looking into GC parameters, so I will open a branch for this and try some stuff

**Comment by sghpjuikit** [comment]
I'm using `"-XX:+UseSerialGC",`. I dont want to provide any premature conclusions.

**Comment by Xerus2000** [comment]
https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/collectors.html

Oracle itself only recommends it for small applications, since it's also quite old. G1GC is default in Java 9 and is most likely the best one for such a monster. For little extra params I am already investigating due to another application, so I'll fix both at once.

**Comment by sghpjuikit** [comment]
I was getting unsupported parameter when trying to tweak G1, so I tried Serial. I'm just experimenting.

**Comment by Xerus2000** [comment]
Wow I acquired a lot of knowledge about Java 8 GC and how to debug it, only to find out now that everything was completely changed in Java 9...

Useful resources:
https://blog.gceasy.io/2017/10/17/43-gc-logging-flags-removed-in-java-9/
http://openjdk.java.net/jeps/158

I am investigating...

**Comment by Xerus2000** [comment]
Java only returns memory back to OS [when the heap is empty to 70%](https://bugs.openjdk.java.net/browse/JDK-8078039) - so using `-XX:MaxHeapFreeRatio=` with a lower value like 30 or 40 seems good. You can append this to `player.jvmArgs` and experiment.

**Comment by Xerus2000** [comment]
Another interesting idea is to have a GC button somewhere on the player that invokes `System.gc()`. That way when you leave the player open in the background but don't want it to eat your resources, then you could push this beforehand.

"MaxHeapFreeRatio" and "MinHeapFreeRatio" can also be adjusted at runtime. so we could create Settings for these, but that will be separated into #65

**Comment by sghpjuikit** [comment]
Invoke CTRL+I (or global CTRL+SHIFT+I) action popup and write "garbage" and invoke the gc action using ENTER key or mouse.

Invoking gc (auto or manually) is a bad alternative to tweaking the gc properly.

I'm willing to consider giving user the choice to tweak the gc, but only if it proves to be untweakable for general use.

**Comment by sghpjuikit** [comment]
I understand that setting "MaxHeapFreeRatio" and "MinHeapFreeRatio" at runtime also makes them take effect? I really think this is a bad idea, but it may be alright to have them work with application restart - i.e., making them take effect when application starts.

I see no reason why the gx should be tweaked at runtime. Again, if the application is taking too much resources, it should be optimized and gc tweaked up front. See Intellij Idea's vm options settings.

One can already run gc manually, which seems like an odd feature, purely for development. We may add an internal plugin that adds these actions/settings and only have it enabled with dev mode as it may be useful for the developer to play around, but if the user is expected to want this then something is horribly wrong.

**Comment by Xerus2000** [comment]
Well, this application is for power users, and power users have obscure use-cases ;) Of course it should be somewhere deep down, but if people want to fiddle with it, why not. Also, it allows you to easier test out useful default parameters without having to restart every time.

**Comment by sghpjuikit** [comment]
Why not - because if we apply this argument, the application would truly take on every problem in the world and do everything. The features should be substantiated. If user wants X and Y as a feature, so be it, there are plugins and widgets for that so the core remains as is. But this is more of a 'lets add this because we can'.

What use case is there for changing free ram ratio in runtime? Is user expected to tune gc of his application depending on how he uses it, in the moment? I'm ok with having this be set when application is started, based on some values in application.properties, but runtime modification is a bad idea.

**Comment by sghpjuikit** [comment]
JDK12 will make it possible for G1 to release memory to OS. https://openjdk.java.net/jeps/346
After adopting JDK12, this issue should be investigated.

**Comment by sghpjuikit** [comment]
It is possible to run this project against jdk12 now.

I have observed default non-tweaked G1 on both jdk11 and jdk12 to release unused memory. In my very preliminary conclusion, it may still be necessary to tweak it in. 

> G1GC is default in Java 9 and is most likely the best one

It seems to me that G1 is intended for cloud and server-deployed application, with its >4GB heap recommendation and throughput>memory intention. For a desktop application that wants to stay small and has little actual garbage (compared to web app bombarded with requests) G1 may actually be a bad choice, even on JDK12.

> button somewhere on the player that invokes System.gc()
This should become available in `developer mode` only (which is available to the user if he enables it). If an application needs user to call gc then something is horribly wrong. At that point we may as well call gc() programmatically periodically or in idle... This is the last resort.

> power users have obscure use-cases
The use cases are known up front, hence we need to ready application for them. We want to return memory to OS as much and as fast as possible as long as it does not interfere with the OS/application performance.

I think using "MaxHeapFreeRatio" and "MinHeapFreeRatio" is a good start, but giving this option to the user should be last resort. Let's first provide sensible default. Options will come later, if they prove necessary.

**Comment by sghpjuikit** [comment]
Im trying out g1 with `-XX:MinHeapFreeRatio=5"` and `-XX:MaxHeapFreeRatio=10`. No performance problems, memory releasing works +-immediately.

**Comment by Xerus2000** [comment]
> Im trying out g1 with `-XX:MinHeapFreeRatio=5"` and `-XX:MaxHeapFreeRatio=10`. No performance problems, memory releasing works +-immediately.

Yes, but memory allocation will get less efficient because it has to cram everything into little free space and regularly resize the memory, which is more expensive.

**Comment by sghpjuikit** [comment]
Indeed. It is a trade off we should carefully consider. However, if there are no lags/slow downs when memory spikes, then I would leave it be aggressively set. I pushed these settings to be the default (experimental) to see if it causes problems.

**Comment by sghpjuikit** [comment]
Current settings seem satisfactory to me so I consider the issue solved.

Possible improvements would be to set gc idle detection timings. Perhaps in the future. I welcome any suggestions and improvements.

**Comment by sghpjuikit** [comment]
Idle gc detection

I notice that sometimes the gc activity or even direct calling System.gc() does not go back to values that the application can achieve when it sits idly for some time. This may be standard behavior or we may actually improve memory footprint by nudging the gc idle detection. This warrants an investigation in the future.
