### ISSUE TITLE
Typing x activates mini mode

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#47]
When opening the application in the background, without having configured it, mini mode often suddenly activates, which is a bit annoying. Apparently the Hotkey is supposed to be F9, but there seems to be another trigger.

Edit: I found out that the x key activates it

**Comment by sghpjuikit** [comment]
By opening in bgr, you mean the guiless mode?

**Comment by Xerus2000** [comment]
No I don't mean the guiless mode, I mean I open it and leave it open in the background. Then, while I type stuff, I randomly hit x and the mini mode pops out of nowhere

**Comment by sghpjuikit** [comment]
That is definitely a bug.
And there should be no shortcuts without modifiers.

**Comment by sghpjuikit** [comment]
I reproduced the bug.

**Comment by sghpjuikit** [comment]
I disabled mini mode shortcut activation so this will no longer be an issue, but the underlying problem may still be present. However jnativehook has been updated so it me not.

I'm closing this and putting up a mind note to do rigorous shortcut testing in the future.
