### ISSUE TITLE
Search Settings

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#49]
Searching through the Settings is always a super handy thing and far too few applications support it. Searching by Keyboard shortcut would also be nice. Somewhat inspired by IDEA here.

**Comment by sghpjuikit** [comment]
Agree. It's been on my personal TODO list for 2 years. The Configurator widget is ready for it, all that remains is do it.

**Comment by sghpjuikit** [comment]
Finally on my immediate todo list.

**Comment by Xerus2000** [comment]
have you considered PreferencesFX?

**Comment by sghpjuikit** [comment]
It is on my radar. I will look into it.

**Comment by sghpjuikit** [comment]
It is now possible to look up a setting or category through application search. This will open the settings with the appropriate category.

**Comment by sghpjuikit** [comment]
Settings search was implemented in c1dbb28
