### ISSUE TITLE
Player messes up path to music file

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#53]
![image](https://user-images.githubusercontent.com/13354331/36809375-0bce4cf6-1cc8-11e8-8ba8-221bafff158a.png)

As you can see in the image, VLC is given a wrong path. It looks like it resolves an absolute file against the Player directory.

**Comment by sghpjuikit** [comment]
I observed this exact issue on Mac OS. I fear this is caused by `"-Duser.dir=$workingDir"`.

**Comment by Xerus2000** [comment]
Fixed by 86cfe202dea6e902eea08f7d0b517a5813ca98e4
