### ISSUE TITLE
Settings window opens mispositioned

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#54]
Right now, when opening the Settings windows, it's top-left edge is in the center of the application. This makes it inconvenient since part of it is then hidden behind the bottom right corner of my screen, and I have to reposition it everytime.

**Comment by sghpjuikit** [comment]
Did not catch this problem until you mentioned it. Thx for reporting.  I'll fix it. Should be relatively easy.

**Comment by sghpjuikit** [comment]
I did fix this issue by loading the widget before the popup is shown. I think this is the correct order and if some widgets have problem with loading before they are visible, there should be a mechanism in place to fix that on part of widget loading.

I'm closing this as general implementation falls outside of this issue.
