### ISSUE TITLE
Disabling global shortcuts on Linux crashes the application silently

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#57]
The issue I encountered is already reported on jnativehook: https://github.com/kwhat/jnativehook/issues/200

When disabling global shortcuts in the settings, I have found that the call to `GlobalScreen.unregisterNativeHook()` in `Hotkeys.stop()` silently terminates the application, no stacktrace, no exception, just instantly dead.

**Comment by Xerus2000** [comment]
This is also the reason why the application for me always exits with exit code 1.

**Comment by sghpjuikit** [comment]
Once again, it appears it does work on my Mint OS.

**Comment by sghpjuikit** [comment]
In case reverting to older build does not help, I suggest defaulting using global hotkeys on Linux to false and only allowing them with a warning (or not at all).

**Comment by sghpjuikit** [comment]
@Xerus2000, you have reverted jnativehook to 2.0.2. Can this issue be closed now?

**Comment by Xerus2000** [comment]
a2a8f935a6f5574fd8dd226b14e7686169cbc8fa
