### ISSUE TITLE
Add Play option to Dir Viewer

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#70]
Since this is in the end still a music player, the Dir Viewer should have an option (in the rightclick menu) to play the file in the player if it is an audiofile.

**Comment by sghpjuikit** [comment]
The appropriate changes can be done in the CoreMenus.kt file. I welcome PR for this. Note that it is necessary toadd the play option for File and List<File> using add and addMany methods. As to how play the file, there already are other play menus, so reuse the code. Use runIf {} to create the menu conditionally.

**Comment by sghpjuikit** [comment]
Implemented.

**Comment by Xerus2000** [comment]
Fixed in https://github.com/sghpjuikit/player/commit/b2fcd1f6eedba35c411e4dfcbe145c7683a1d7d6

Please remember to always mention the commit for archiving purposes.

**Comment by sghpjuikit** [comment]
Right, I apologize. Keep forgetting. Always remind me if I mess up. I'll make it a habit.
