### ISSUE TITLE
Java version enforcement on project setup

### ISSUE THREAD

**Issue by sghpjuikit** [sghpjuikit/player#76]
Problem1:
Developer who has older java version set as default will continue being unable to set up and build project even if he links or copies uptodate jdk to the project (workindDir/java). 

Problem2:
The error also does not help developer in any way to solve the problem.

**Comment by sghpjuikit** [comment]
Indeed. I.m closing the issue. But I will try to figure out why setting java home in properties had no effect on my machine.

**Comment by Xerus2000** [comment]
Ah, there's a common Windows pitfall you might have fallen into: If you use backslashes in the path, you need to use double backslashes, because they are, as everywhere, escape characters!

**Comment by sghpjuikit** [comment]
I think I checked this one, but I'll give it another shot, thx.
