### ISSUE TITLE
Add column for VBR and group columns

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#9]
1. To check if the Song is VBR, use AudioFile.getAudioHeader().isVariableBitRate()
2. Put the Columns into groups, because many of them are completely irrelevant for normal use
![columns](https://user-images.githubusercontent.com/13354331/32416837-cf8ae2ea-c24f-11e7-9f20-5bfe9ee0a970.png)
preferably these groups should then be customizable, but to get started it would probably be nice to directly see the most important columns (Album, Artist, Title, Playcount, Rating, maybe some more), a group for the other ones, and then a group for Custom1-5, to prevent the popup from filling the screen.
3. What does the Color Tag do?

**Comment by sghpjuikit** [comment]
1 Sure. But Instead of creating a new field, Bitrate class should be modified to carry this information.
2 How do you propose the grouping is done? I do not like the idea of arbitrary groups much. I do agree the way it is has issues.
3 It allows one to associate a color with the song.

**Comment by sghpjuikit** [comment]
1 I have included the variable bitrate information into the Bitrate class. I also added appropriate filters. However, I am still not sure how to handle variable bitrate values. Jaudiotagger reports some value even if it reports variable bitrate, maybe it is an average. For now, I ignore this value. This may be improved in the future.

2 I'll fix this one along the way, when I figure something out. I consider this a very small UX problem so I'm closing this entire issue now.

**Comment by Xerus2000** [comment]
Usually you would just say like "187 kbps VBR". And yeah, it's an average, which jaudiotagger obtains from the header, which is written by the encoder.

**Comment by sghpjuikit** [comment]
Then Bitrate class could be enhanced to display this information. I'll look into it soon.

**Comment by sghpjuikit** [comment]
Fixed. Variable bitrate values use ~ prefix.
